# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: rvasilevsk
# description: >- 
#   [A short description]

domain: rvasilevsk.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://rvasilevsk.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /ghpages-jekyll/      # place folder name if the site is served in a subfolder
github_username:  rvasilevsk
# twitter_username: jekyllrb
# email: your-email@example.com


# Build settings
theme: minima
# theme: cayman
plugins:
  - jekyll-feed
  # - jekyll-remote-theme

# cayman`s vars 
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/




# minima
#   favicon
#     path: path/to/favicon.[png|svg] # browsers are supporting svgs now
#     permalink: ...
